environment:
  JULIA_DEBUG: CUDAapi
  matrix:
  # Julia versions
    # No CUDA
  - julia_version: 1.0
    cuda_version: nil
  - julia_version: 1.2
    cuda_version: nil
  - julia_version: 1.3
    cuda_version: nil
  - julia_version: latest
    cuda_version: nil
    # CUDA 8.0
  - julia_version: 1.0
    cuda_version: 8.0
  - julia_version: 1.2
    cuda_version: 8.0
  - julia_version: 1.3
    cuda_version: 8.0
  - julia_version: latest
    cuda_version: 8.0

  # CUDA versions on 1.0
  - julia_version: 1.0
    cuda_version: 9.0
  - julia_version: 1.0
    cuda_version: 9.1
  - julia_version: 1.0
    cuda_version: 9.2
  - julia_version: 1.0
    cuda_version: 10.0
  - julia_version: 1.0
    cuda_version: 10.1
  # CUDA versions on latest
  - julia_version: latest
    cuda_version: 9.0
  - julia_version: latest
    cuda_version: 9.1
  - julia_version: latest
    cuda_version: 9.2
  - julia_version: latest
    cuda_version: 10.0
  - julia_version: latest
    cuda_version: 10.1

platform:
  - x64

matrix:
 allow_failures:
  - julia_version: latest
    cuda_version: 8.0
  - julia_version: latest
    cuda_version: 9.0
  - julia_version: latest
    cuda_version: 9.1
  - julia_version: latest
    cuda_version: 9.2
  - julia_version: latest
    cuda_version: 10.0
  - julia_version: latest
    cuda_version: 10.1

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - powershell .\.appveyor.ps1
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
